FILES_DIRECTORY: /app/data
FILES_QUEUE_SIZE: 100
FILES_SPLIT_QUEUE_SIZE: 100
MAX_FILE_SIZE_BYTES: 10485760
DATA_BATCH_SIZE: 10000
DATA_BATCH_QUEUE_SIZE: 1000
IMPORT_BY_LINES: false
WORKERS_COUNT: 10
FILE_SCANNER:
  CHECK_EVERY_DURATION: 5s
FILE_SPLITTER:
  WORKERS_COUNT: 10
  LINES_QUEUE_SIZE: 100
  SPLIT_BY_LINES: 100000
STORAGE:
  TYPE: mysql
  MAX_CONNECTIONS: 2000
  DSN: prices:1q2w3e@tcp(mysqldb:3306)/prices?allowAllFiles=true&parseTime=true