// Code generated by MockGen. DO NOT EDIT.
// Source: prices.go

// Package service is a generated GoMock package.
package service

import (
	context "context"
	models "prices/pkg/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPrices is a mock of Prices interface.
type MockPrices struct {
	ctrl     *gomock.Controller
	recorder *MockPricesMockRecorder
}

// MockPricesMockRecorder is the mock recorder for MockPrices.
type MockPricesMockRecorder struct {
	mock *MockPrices
}

// NewMockPrices creates a new mock instance.
func NewMockPrices(ctrl *gomock.Controller) *MockPrices {
	mock := &MockPrices{ctrl: ctrl}
	mock.recorder = &MockPricesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrices) EXPECT() *MockPricesMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockPrices) Get(ctx context.Context, id string) (*models.Price, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*models.Price)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPricesMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPrices)(nil).Get), ctx, id)
}
